title: Shifeng XIE
url: https://shifengxie.github.io

owner:
  name: Shifeng XIE
  avatar: ./photo.jpg

links:
  - title: About Me
    url: /
  - title: Publications
    url: /publications/
  - title: Awards
    url: /awards/

timezone: Europe/Paris
future: true
highlighter: rouge

permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "minimal-mistakes.sublime-project", "minimal-mistakes.sublime-workspace"]
