title: Shifeng XIE
url: https://shifengxie.github.io

owner:
  name: Shifeng XIE
  avatar: profile-photo.png

links:
  - title: About Me
    url: /
  - title: Publications
    url: /publications/
  - title: Awards
    url: /awards/

timezone: Europe/Paris
